### ISSUE TITLE
Val av Korp backend i konfig fil

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-mfl#11]
Det vore extremt bra om man kan ändra base-url:en till Korp som används av Mfl genom konfigfilen.
Och sa borde minimum versionen av Korp backend instansen anges i dokumentationen...

**Comment by kristiank** [comment]
Kan jag ändra url-variabeln genom javascript i webbläsaren innan detta kan anges i konfigen? Som en temporär lösning?

**Comment by majsan** [comment]
Du kan ändra den i `src/config.json`. Det måste göras innan man bygger frontenden dock (kommer att ändras i framtiden).
