### ISSUE TITLE
Visa lemma eller lemgram istället för siffra

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-mfl#12]
Under "Få förslag" om ordformen passar flera paradigm sa visas dessa som siffror längs ned pa sidan.
Jag har tre förslag:
1. visa lemma eller lemgram istället för siffra
2. visa "Passande paradigm" framför länkarna
3. (kanske) flytta upp raden med länkar till passande paradigm ovanför "översiktspanelen" (där alla ordformerna visas till vänster och variabel- och lemgramsinformationen visas till höger)

**Comment by majsan** [comment]
Menar du sidbläddraren?

Alla förslag har samma lemgram ifyllt isåfall. Men det är en god idé att skriva något annat där, t.ex. paradigm som är unikt för varje förslag.

Den skulle nog kunna flytta upp också. Ett annat förslag som har tagits upp är att visa flera samtidigt, men då vill vi först att backenden ska kunna berätta om förslagen är ungefär lika bra.

**Comment by MalinAhlberg** [comment]
Vad innebär "ungefär lika bra"? Backenden skickar ju med en `score` som (förhoppningsvis) visar om ett förslags braighet ligger i närheten av ett annats.

**Comment by majsan** [comment]
Jag vet inte vad det innebär. Men vi måste tänka igenom vilka förslag vi vill visa sida vid sida eller ej. Det är möjligt att vi isåfall kommer fram till att `score` duger för att veta det. Eller så visar man alltid de två första.

**Comment by kristiank** [comment]
Jag tror att det kan bli ganska rörigt om man visar flera förslag på en gång, men kanske är ni inne på nåt som är bra, för jag känner att det paradigm som visas (eller de paradigm, om det nu visas flera) måste på nåt sätt tydligare namnges. Och det var detta jag ville att man gör istället för att visa siffra -- att man visar paradigmets namn.

Så till exempel. Om jag söker efter förslag på en ordform "röntüz", så får jag just nu två passande paradigm (p3_lentüz..nn.1 och p5_tüttö..nn.1). Dessa visas för tillfället som två siffror som länkar nedantill, det är helt omöjligt att veta vad dessa siffror menar. Jag skulle nästan vilja se att användargränsnittet skulle fråga mig en fräga "Menar du _röntüz_ som böjs enligt _lentüz_ eller enligt _tüttö_?" Eller att siffrorna byts ut med paradigmnamnen.

En annan variant vore att ha paradigmnamnet som en sorts "titel" till ordformstabellen. Då skulle man kunna ha flera tabeller bredvid varandra. Men eftersom de föreslagna paradigmen har sina `score`, så skulle man kunna visa en lista av paradigmnamnen tillsammans med `score`. Men eftersom gränssnittet redan nu består av två delar (ordformstabellen till vänster och lite extra info till höger) så är det väl svårt att visa ännu en vertikal lista med paradigmnamn och `score`.

**Comment by majsan** [comment]
Vi börjar med att byta ut siffrorna mot paradigmnamnen och fortsätter fundera på de övriga förslagen.
