### ISSUE TITLE
Hur benämna paradigm, deklinationer, bklasser...?

### ISSUE THREAD

**Issue by MalinAhlberg** [spraakbanken/karp-mfl#3]
Vi behöver bra namn på saker. Vad kallar vi tex:

1. pextractparadigm
2. användarnas egna böjningsmönster, får de döpa dem till vad som helst?
3. användarnas egna böjningsmönster, samlingsnamn för alla sådana
4. samlingsnamn för alla slags böjningsmönster, både pextracts och människornas

Både engelska och svenska namn behövs.

**Comment by MalinAhlberg** [comment]
`2.` kan ju hanteras genom configer; användaren skriver tex
{"X": [{"name": "b-klasser", "path": "FormRep.bklass"}, {"name": "c-klasser", "path": "FormRep.cklass"}]}

där "X"är namnet på `3.`

**Comment by kristiank** [comment]
1. pextractparadigm
Menar du här grovt sagt pfilens `1+a+2:msd`?
Hur orakel-specifika måste vi vara? Om inte alls, så kanske `extractparadigm` och `extraktparadigm`?

2. användarnas egna böjningsmönster, får de döpa dem till vad som helst?
Menar du här en av variablar instansierad ordform av ett ekstraktparadigm? Jag kan föreställa mig situationen i frontenden som "välj som `mönsterord`".
Jag tycker inte att användare ska få döpa dem till vad som helst, utan det måste vara en reell variabelinstansiering. Därmed kan döpandet vara funktionellt: namned för paradigmet är första variabelinstansieringen som finns lagrad i paradigm jsonet i Karp. Om användaren döper om den, flyttas bara en variabelinstansiering till början av den långa raddan i paradigm jsonet.

3. användarnas egna böjningsmönster, samlingsnamn för alla sådana
Samma som nedanstående. Jag tycker inte användaren ska behöva göra skillnad mellan pextract paradigm och "lexikografiska" paradigm, eftersom ett paradigm är ju definerat av sig självt: ett paradigm är alla ordformerna som det innehåller. Matthews (1991): "[...] paradigms . These are sets of words as wholes, arranged according to grammatical categories."

4. samlingsnamn för alla slags böjningsmönster, både pextracts och människornas
Jag har inte boken tillhands, men Svensén i sin Handbok i lexikografi (2004) kallar väl det för `mönsterparadigm`.

5. ordformer som är input till en paradigmfunktion
Lägger till den här, kanske blir relevant. Pextract har bara en ordform som input, men GF Smart Paradigms har ofta fler. Dessa kallar Svensén `temaformer`.

**Comment by kristiank** [comment]
Jag ska försöka läsa lite i Stump's och Finkel's bok ikväll. De har en massa benämningar och kanske kan vi använda till engelska varianten av `mönsterparadigm` nånting därifrån.

Stump, Gregory & Raphael A. Finkel. 2013. Morphological Typology: From Word to Paradigm.

**Comment by MalinAhlberg** [comment]
1,3,4,5: :+1: 

2. Jag uttryckte mig lite luddigt, insåg jag. Det här gäller alltså tex pedagogiska paradigm/böjningsklasser. Men å andra sidan är detta kanske inte ett problem, insåg jag i min egen kommentar ovan :P 
Jag är inte säker på att jag inte tycker att användaren ska få döpa dem till vad hen vill. Det kan väl vara tex pedagogiskt att man får använda samma terminologi som sin skolbok om man vill?

**Comment by kristiank** [comment]
2. böjningsklasser alltså, inte paradigm. Matthews kallar det för `inflectional class` och svenskans `böjningsklass` är väl okej? Och absolut -- böjningsklasser går inte att deducera från variabelinstanserna ;-)

(Att LMF kallar det för TransformCategory är helt orelevant, dock borde ju det fältet heta så även i json varianten ...)

**Comment by kristiank** [comment]
2. LMF Morphological Patterns kan innehålla benämningar för böjningsklasser och andra klasser. Jag la till det i lmf-json igår: https://github.com/spraakbanken/karp-mfl/pull/2#issuecomment-373113049
Detta borde väl vara direkt anknytet till din configgrej?

**Comment by MalinAhlberg** [comment]
Jag är lite förvirrad. Är det skillnad på böjningsklass/inflectional class och mönsterparadigm, eller var det förslag till samma sak?
2. Ja, det borde anknyta till det! Ska trassla mig ur härvan av begrepp och kod jag sitter med nu, och kolla på detta!

**Comment by kristiank** [comment]
En klass är ju en grupp eller mängd av objekt som har nåt gemensamt. Vad jag förstått så är deklinationer/konjugationer `böjningsklasser`. En `böjningsklass` vore därmed snäppet abstraktare än paradigm/böjningsmönster/mönsterparadigm. Alltså `böjningsklass` är en klass (en grupp, en mängd) av paradigm.

**Comment by kristiank** [comment]
Med andra ord: mönsterparadigm är benämningen för en enstaka paradigmfunktion. Dess namn är direkt kopplat till variabelinstansiering.

Flera _liknande_ paradigm kan tillhöra en böjningsklass, men de är bara _liknande_, inte exakt samma (de delar inte samma paradigmfunktion).

**Comment by kristiank** [comment]
Ahaa! Jag missförstod ditt `böjningsmönster` (i punkt 2 och 3). Jag trodde du menade en människas benämning på ett extraktparadigm, men du menade böjningsklass, inte böjningsmönster? Usch, nu är jag tillbaka på ruta ett.

**Comment by MalinAhlberg** [comment]
Ja, jag menade "böjningsklass" i 2 och 3 :) Tror jag, det är svårt att prata om terminologi innan den blivit fastslagen :/ Oavsett tror jag att det börjar klarna! Mina utgångstankar om det här var kanske för luddiga, men jag kommer göra en pull request med någon slags exempelconfig ganska snart. Där kanske det blir mindre tvetydigt, så kan vi diskutera mer utifrån den.

**Comment by kristiank** [comment]
Ja, jag håller med. Och kanske är `kategori` bäst som benämnimg...

**Comment by kristiank** [comment]
Terminologi är samma som datorsäkerhet: funkar bäst när det är bara en användare.

**Comment by kristiank** [comment]
Försöker dra samman här, kanske är till hjälp inför måndagens möte.

> 1. pextractparadigm

Ekstraktparadigm eller bara paradigm.
> 2. användarnas egna böjningsmönster, får de döpa dem till vad som helst?

Ett namngett ekstraktparadigm = mönsterparadigm. Fast jag kan föreställa mig situationen i frontenden som "välj som mönsterord".
Användaren får döpa dom enbart enligt attesterade variabelinstanser.
> 3. användarnas egna böjnings**klasser**, samlingsnamn för alla sådana

Böjningsklass eller klass eller kategori.
> 4. samlingsnamn för alla slags böjningsmönster, både pextracts och människornas

Den är lite klurig, eftersom det innefattar både paradigm och böjningsklasser (alltså samlingar av paradigm). Fast rent principiellt skulle det ju gälla att:
de kallas enligt `1` och `2` om det gäller bara ett paradigm;
de kallas enligt `3` om det gäller fler än ett paradigm.
> 5. input-former till paradigmfunktion eller smarta paradigmfunktioner

de kallas lemma eller grundform om det gäller bara en form som input;
de kallas teman eller temaformer om det gäller fler än en form som input.

**Comment by MalinAhlberg** [comment]
Nu stänger jag här och så fortsätter vi diskussionen i relation till förslag för API/gränssnitt/configar.
