### ISSUE TITLE
Inloggning försvinner

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-mfl#9]
Om jag klickar pa "morfologilabbet" (högst upp till vänster) sa försvinner min inloggning och jag maste logga pa nytt.

**Comment by majsan** [comment]
Det här händer enbart om man väljer inte väljer "Spara inloggningen" antar jag. Vi har inte stöd för cookies i inloggningen, så det går inte att göra något åt just nu.

I framtiden så kommer vi att uppgradera till ett annat inloggningssystem och då kommer problemet att lösas. Stänger.
